### ISSUE TITLE
Support touch screens in GUI navigation

### ISSUE THREAD

**Issue by GlenDC** [threefoldfoundation/tfchain-wallet-electron#118]
My original thought was that touch screens (laptops that have a touch screen) don't require special support and simply use the regular mouse-based controls under the hood. We have a user now with such a window-based touch-screen-enabled laptop and it seems that not all GUI elements behave as nicely with the touch controls as the user expects.

Investigate if special attention is required and if so add support for it.

**Comment by DylanVerstraete** [comment]
Known issue https://github.com/electron/electron/issues/17552

**Comment by DylanVerstraete** [comment]
Related issue https://github.com/electron/electron/issues/8725
