### ISSUE TITLE
opening settings page from wallet opens account settings page

### ISSUE THREAD

**Issue by GlenDC** [threefoldfoundation/tfchain-wallet-electron#176]
When pressing the settings page from a wallet page (using the settings button), it opens up the account settings page:

- it should really open the wallet settings page
- there is no going back button (I guess this might be normal in the new design?)
- the cancel button goes to the account page, even though we were in a wallet page

**Comment by DylanVerstraete** [comment]
This design will lead to bad UX. It's better for the user if a page always shows the same content. Else the user will be confused.
