### ISSUE TITLE
No toasts on linux when receiving transaction

### ISSUE THREAD

**Issue by LeeSmet** [threefoldfoundation/tfchain-wallet-electron#220]
Toasts are received for copy to clipboard though

tested on notifcations branch

**Comment by DylanVerstraete** [comment]
[https://electronjs.org/docs/api/app#appsetbadgecountcount-linux-macos](https://electronjs.org/docs/api/app#appsetbadgecountcount-linux-macos)

On Linux, it only works for Unity launcher.

So we can only target Ubuntu, wontfix for other linux environments since there is no API available.
