### ISSUE TITLE
question: should we show "locked until ..." in transaction list if still locked

### ISSUE THREAD

**Issue by GlenDC** [threefoldfoundation/tfchain-wallet-electron#38]
Currently (Coin) Output(s) shown in the Transaction List that are still locked, are not shown yet. Should we show it? If so, could you do it.

Not sure if we should do this only for incoming outputs or also outgoing, but for sure I think the incoming ones should have it.

**Comment by GlenDC** [comment]
Any input on this one @DylanVerstraete???

**Comment by DylanVerstraete** [comment]
We now show locked input/outputs in the transaction list.
closed in https://github.com/threefoldfoundation/tfchain-wallet-electron/commit/a11e71f71ff75faeba276490df2747cf2417d600
