### ISSUE TITLE
show unconfirmed balance (unlocked and locked) in wallet/account pages

### ISSUE THREAD

**Issue by GlenDC** [threefoldfoundation/tfchain-wallet-electron#39]
This is important. As currently one might be able to get quite some money back (because of unconfirmed refund coin outputs) but this is not shown in balance, only in the transactions list.

**Comment by DylanVerstraete** [comment]
closed in https://github.com/threefoldfoundation/tfchain-wallet-electron/commit/388fe4baa6d8b8b8dccbc3f10e60b6b2702dae3e
