### ISSUE TITLE
when repeatedly pressing 'go back' from acount <-> wallet, user gets logged out and can't log in

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldfoundation/tfchain-wallet-electron#42]
Error from api when trying to log in:

`account data of version {} is not supported`

**Comment by GlenDC** [comment]
Tried to reproduce but didn't manage. Tried with different accounts, different wallets, all kind of crazy stuff, nothing made me log out. Did add log statement in d645fe0 that logs the data as received from the frontend code, might help in reproducing it.

@DylanVerstraete could you try to reproduce it again. Prior to that, can you just post the JSOn data here from the account from which you were logged out (and cannot login again?). Might already explain the answer.

**Comment by DylanVerstraete** [comment]
Can't reproduce anymore, closing this
