### ISSUE TITLE
inputs/outputs on a specific block are not shown when asked for with last_block_get

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldfoundation/tfchain-wallet-electron#47]
Block where input is defined: https://explorer.testnet.threefoldtoken.com/hash.html?hash=c4ac7dea8a26de123cb739855af953c19d3bfb0fa90abf97c91d9e4b83118f87

**Comment by GlenDC** [comment]
Closed in dbe1395359dacea035808f6cf15d6c3bf229839c.
