### ISSUE TITLE
error when fetching account balance 

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldfoundation/tfchain-wallet-electron#48]
stacktrace: `transaction version 144 is unknown`

**Comment by GlenDC** [comment]
Closed by a312a7339eca52921ba3dd365c25a74a9d0d85f8.

We now consume transactions with unknown versions as OpaqueTransactions, which means we might miss some data (coin outputs) but at least the app will continue to work.

Will log a warning though, so as developer we are aware of this.
