### ISSUE TITLE
Create MultiSig wallet page

### ISSUE THREAD

**Issue by GlenDC** [threefoldfoundation/tfchain-wallet-electron#62]
- will be used as the wallet page for any multisig wallet
- by default a multisig wallet has no label, but one can be given
- will have everything a regular wallet page has, but perhaps on top of that we also want to show all co-owners (also making it clear what our addresses of those co-owner addresses are) as well as how many signatures required (e.g. if 2 signatures are required and there are 3 co-owners than we can call it a 2-of-3 MultiSignature wallet);

**Comment by GlenDC** [comment]
Every wallet (cached or not) (same goes for multisig) now has the following properties:

```javascript
wallet.is_cached // indicates if the wallet is cached and thus
                            // if balance returns the balance directly and the balance
                            // will be used from cache and updated when doing stuff
                            // like `transaction.new().send()`.
wallet.has_signing_power // returns if the wallet has keys to sign with,
                                       // if this returns False, do not use transaction_new or transaction_sign,
                             // for such wallets disable this functionality
                            // (receiving is still possible of course)
```

Repeat of properties you already know:

```javascript
wallet.wallet_name
wallet.address
wallet.addresses
wallet.address_count
wallet.balance // (promise for non-cached wallets, and balance object for cached wallet)
```

functions that all wallets have (but do not use for wallets where `wallet.has_signing_power == false`:

```javascript
wallet.transaction_new() // returns a builder, as you're used to
wallet.transaction_sign() // as you're used to as well
```

---

Each time the Account balance refreshes, create your wallets as follows:

```javascript
account.balance.then(ab => {
    // NOTE: MAKE FIRST TO ALWAYS FIRST ASSIGN THE
    //       REGULAR WALLET AND ONLY THEN THE MULTISIG WALLETS
    //       (as best practice)
    state.wallets = [account.cached_wallet_for(balance) for balance in ab.balances]
    state.multisig_wallets = [account.cached_multisig_wallet_for(balance) for balance in ab.multisig_balances]
    // NOTE: please sort the multisig_wallets yourself in the following way:
    // put the multisig wallets with names first and order those by name (`.wallet_name`),
    // put the ms wallets with no name at the end and order these by address
})
```

The static MultiSigWallets you get from the account using `account.multisig_wallets` do implement the regular wallet interface but have `wallet.has_signing_power == false`, so make sure that in case that property is false to disable the transaction send and sign functionalities as it won't yet work.

**Comment by DylanVerstraete** [comment]
added in https://github.com/threefoldfoundation/tfchain-wallet-electron/commit/b3dcc6cd31b88fa0e3049f355b2dc151060e9555

needs some small extra work

**Comment by GlenDC** [comment]
Done.
