### ISSUE TITLE
add receive screen (reachable via wallet screen)

### ISSUE THREAD

**Issue by GlenDC** [threefoldfoundation/tfchain-wallet-electron#7]
The receive screen should allow you to:
 - select the address of a wallet you want to receive on (by default the first address is selected);
 - optionally define an amount (in TFT) you want to receive (0 by default);
 - it will generate a QR Code that can be scanned (e.g. by the official ThreeFold Mobile App):
   - in order for this to work the QR code has to have the following encoded data: `tf:<address>`, when the amount is defined it has the following format: `tf:<address>?amount=<amount>`, examples:
     - without amount: `tft:0101ad716472a30f782fb70c12abff65dfeac358b22b4b9be1c13f82cd413942d0945ed6e5a98e`;
     - with amount: `tft:010557d6dc3d15ac8c2be20cb2fd9b16d97aca6ae72365854f1719c4804bea86410eb6ebc3957a?amount=100.30`;

I don't think it matters too much what QR code library you use, as long as it works.

Can be tested on testnet using the official Threefold App;

**Comment by DylanVerstraete** [comment]
added in https://github.com/threefoldfoundation/tfchain-wallet-electron/commit/a7a1ef1971a8f5b84e12f7745b973a80a759ea56
