### ISSUE TITLE
investigate if we can/should use AppImage for our Linux users

### ISSUE THREAD

**Issue by GlenDC** [threefoldfoundation/tfchain-wallet-electron#81]
<https://appimage.org>

**Comment by xmonader** [comment]
it seems to work fine
- requires libfuse (which is popular) for linux user (e.g used for sshfs, ipfs) 
- size generated 70mb for the wallet
- built easily with `yarn package-linux`

icons seems to be bundled incorrectly in the generated binary

**Comment by GlenDC** [comment]
Please investigate the remaining issues when you can.

**Comment by GlenDC** [comment]
Any progress @xmonader?

**Comment by xmonader** [comment]
@GlenDC I'll fix the icons problem & document and close it on sunday
