### ISSUE TITLE
error refreshing wallet balances (not always)

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldfoundation/tfchain-wallet-electron#89]
_redefine.js:30 Uncaught (in promise) TypeError: Function.prototype.toString requires that 'this' be a Function
    at Function.toString (<anonymous>)
    at Function.toString (_redefine.js:30)
    at tfchain.polyfill.jsmods.promisepooljs.py:2
toString @ _redefine.js:30
(anonymous) @ tfchain.polyfill.jsmods.promisepooljs.py:2
Promise.catch (async)
module.exports../app/tfchain/tfchain.polyfill.jsmods.promisepooljs.js.PromisePool._trackPromise @ tfchain.polyfill.jsmods.promisepooljs.py:2
module.exports../app/tfchain/tfchain.polyfill.jsmods.promisepooljs.js.PromisePool._proceed @ tfchain.polyfill.jsmods.promisepooljs.py:2
(anonymous) @ tfchain.polyfill.jsmods.promisepooljs.py:2
module.exports../app/tfchain/tfchain.polyfill.jsmods.promisepooljs.js.PromisePool.start @ tfchain.polyfill.jsmods.promisepooljs.py:2
promise_pool_new @ tfchain.polyfill.asynchronous.py:88
(anonymous) @ api.py:728
(anonymous) @ org.transcrypt.__runtime__.py:4
Promise.then (async)
chain @ tfchain.polyfill.asynchronous.py:30
(anonymous) @ api.py:676
(anonymous) @ org.transcrypt.__runtime__.py:4
dispatch @ index.js:107
(anonymous) @ /Users/dylan/tfchain-wallet-electron/node_modules/redux-thunk/lib/index.js:11
dispatch @ VM107:1
setBalance @ Root.js:23
intervalID.setInterval @ Root.js:67
setInterval (async)
componentWillMount @ Root.js:65
callComponentWillMount @ /Users/dylan/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:11421
mountClassInstance @ /Users/dylan/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:11514
updateClassComponent @ /Users/dylan/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:14688
beginWork @ /Users/dylan/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:15644
performUnitOfWork @ /Users/dylan/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:19312
workLoop @ /Users/dylan/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:19352
renderRoot @ /Users/dylan/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:19435
performWorkOnRoot @ /Users/dylan/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:20342
performWork @ /Users/dylan/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:20254
performSyncWork @ /Users/dylan/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:20228
requestWork @ /Users/dylan/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:20097
scheduleWork @ /Users/dylan/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:19911
scheduleRootUpdate @ /Users/dylan/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:20572
updateContainerAtExpirationTime @ /Users/dylan/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:20600
updateContainer @ /Users/dylan/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:20657
ReactRoot.render @ /Users/dylan/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:20953
legacyRenderSubtreeIntoContainer @ /Users/dylan/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:21105
render @ /Users/dylan/tfchain-wallet-electron/node_modules/react-dom/cjs/react-dom.development.js:21155
(anonymous) @ index.js:21
(anonymous) @ index.js:17
hotApply @ bootstrap:631
(anonymous) @ bootstrap:313
Promise.then (async)
hotUpdateDownloaded @ bootstrap:312
hotAddUpdateChunk @ bootstrap:288
webpackHotUpdateCallback @ bootstrap:7
(anonymous) @ main.e56b228c92b6abbb7410.hot-update.js:1
redux-logger.js:1  action GET_TX_FOR_WALLET @ 16:21:17.734
redux-logger.js:1  action SET_BALANCE @ 16:21:18.209
redux-logger.js:1  action SET_CHAIN_CONSTANTS @ 16:21:18.272

**Comment by GlenDC** [comment]
Fixed and merged into master.
