### ISSUE TITLE
error in transfer to multisig wallet

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldfoundation/tfchain-wallet-electron#95]
"cannot add public_key ed25519:643ceecf40b910d441db7e4f90de49c7e6f79eadff052f8ee187d4d365df993f as it already exists within a pair of this MultiSignature Fulfillment"

Occurs in builder.send(...), error is not thrown so can't be catched by frontend

**Comment by GlenDC** [comment]
Closed in master.
